# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FTP-Build-And-Deploy-Action:
    name: FTP-Build-And-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build Project
      env:
       REACT_APP_FIREBASE_APIKEY: ${{ secrets.REACT_APP_FIREBASE_APIKEY }}
       REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
       REACT_APP_FIREBASE_AUTHDOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTHDOMAIN }}
       REACT_APP_FIREBASE_DATABASEURL: ${{ secrets.REACT_APP_FIREBASE_DATABASEURL }}
       REACT_APP_FIREBASE_MESSAGINGSENDERID: ${{ secrets.REACT_APP_FIREBASE_MESSAGINGSENDERID }}
       REACT_APP_FIREBASE_PROJECTID: ${{ secrets.REACT_APP_FIREBASE_PROJECTID }}
       REACT_APP_FIREBASE_STORAGEBUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGEBUCKET }}
       REACT_APP_GIPHY_APIKEY: ${{ secrets.REACT_APP_GIPHY_APIKEY }}
      run: |
        npm install
        npm run build --if-present
  
    - name: List output files
      run: ls
    
    - name: FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{ secrets.FTP_SERVER }}
        # ftp username
        username: ${{ secrets.FTP_USERNAME }}
        # ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # Folder to upload from, must end with trailing slash /
        local-dir: ./build/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: ./html/gh-actions/

